tap "adoptopenjdk/openjdk"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "ringohub/redis-cli"
tap "thecasualcoder/stable"
tap "theeternalsw0rd/telnet"
brew "act"
brew "python@3.9"
brew "awscli"
brew "bat"
brew "deno"
brew "direnv"
brew "fasd"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "helm"
brew "httpie"
brew "jq"
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubectx"
brew "mas"
brew "minikube"
brew "mysql-client"
brew "openjdk"
brew "pipenv"
brew "pyenv"
brew "stern"
brew "telnet"
brew "terraform"
brew "tree"
brew "wget"
brew "wrk"
brew "yq"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "ringohub/redis-cli/redis-cli"
brew "thecasualcoder/stable/kube-fzf"
cask "1password"
cask "adoptopenjdk11"
cask "adoptopenjdk8"
cask "aerial"
cask "alfred"
cask "authy"
cask "aws-vault"
cask "bloomrpc"
cask "datagrip"
cask "docker"
cask "dropbox"
cask "easy-move-plus-resize"
cask "firecamp"
cask "font-hack-nerd-font"
cask "goland"
cask "google-backup-and-sync"
cask "intellij-idea"
cask "iterm2"
cask "itsycal"
cask "keybase"
cask "keyboard-maestro"
cask "kitematic"
cask "mysqlworkbench"
cask "notion"
cask "obsidian"
cask "postman"
cask "pycharm"
cask "sourcetree"
cask "sublime-text"
cask "telegram-desktop"
cask "visual-studio-code"
cask "webstorm"
cask "zoom"
mas "KakaoTalk", id: 869223134
mas "Keynote", id: 409183694
mas "Melon", id: 1236050766
mas "Numbers", id: 409203825
mas "Owly", id: 882812218
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
